// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"backend/internal/biz"
	"backend/internal/conf"
	"backend/internal/data"
	"backend/internal/server"
	"backend/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, storage *conf.Storage, nats *conf.NATS, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	client := data.NewRedisClient(confData, logger)
	minioClient := data.NewMinIOClient(storage, logger)
	conn := data.NewNATSConn(nats, logger)
	dataData, cleanup, err := data.NewData(db, client, minioClient, conn, logger)
	if err != nil {
		return nil, nil, err
	}
	authRepo := data.NewAuthRepo(dataData, logger)
	authUsecase := biz.NewAuthUsecase(authRepo, auth, logger)
	authService := service.NewAuthService(authUsecase)
	categoryRepo := data.NewCategoryRepo(dataData, logger)
	categoryUsecase := biz.NewCategoryUsecase(categoryRepo, logger)
	categoryService := service.NewCategoryService(categoryUsecase)
	tagRepo := data.NewTagRepo(dataData, logger)
	tagUsecase := biz.NewTagUsecase(tagRepo, logger)
	tagService := service.NewTagService(tagUsecase)
	videoCache := data.NewVideoCache(dataData, logger)
	videoRepo := data.NewVideoRepo(dataData, videoCache, logger)
	channelRepo := data.NewChannelRepo(dataData, logger)
	membershipChecker := data.NewMembershipChecker(channelRepo)
	videoUsecase := biz.NewVideoUsecase(videoRepo, tagUsecase, membershipChecker, logger)
	videoService := service.NewVideoService(videoUsecase)
	searchRepo := data.NewSearchRepo(dataData, logger)
	searchUsecase := biz.NewSearchUsecase(searchRepo, logger)
	searchService := service.NewSearchService(searchUsecase)
	channelUsecase := biz.NewChannelUsecase(channelRepo, logger)
	channelService := service.NewChannelService(channelUsecase)
	grpcServer := server.NewGRPCServer(confServer, auth, logger, authService, categoryService, tagService, videoService, searchService, channelService)
	minIOUploader := data.NewUploader(minioClient, storage)
	httpServer := server.NewHTTPServer(confServer, auth, logger, authService, categoryService, tagService, videoService, searchService, channelService, minIOUploader)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
