// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: fenzvideo/v1/admin.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_AdminListUsers_FullMethodName   = "/fenzvideo.v1.AdminService/AdminListUsers"
	AdminService_AdminDeleteUser_FullMethodName  = "/fenzvideo.v1.AdminService/AdminDeleteUser"
	AdminService_AdminListVideos_FullMethodName  = "/fenzvideo.v1.AdminService/AdminListVideos"
	AdminService_AdminDeleteVideo_FullMethodName = "/fenzvideo.v1.AdminService/AdminDeleteVideo"
	AdminService_AdminCreateTag_FullMethodName   = "/fenzvideo.v1.AdminService/AdminCreateTag"
	AdminService_AdminUpdateTag_FullMethodName   = "/fenzvideo.v1.AdminService/AdminUpdateTag"
	AdminService_AdminDeleteTag_FullMethodName   = "/fenzvideo.v1.AdminService/AdminDeleteTag"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	AdminListUsers(ctx context.Context, in *AdminListUsersRequest, opts ...grpc.CallOption) (*AdminListUsersReply, error)
	AdminDeleteUser(ctx context.Context, in *AdminDeleteUserRequest, opts ...grpc.CallOption) (*AdminDeleteUserReply, error)
	AdminListVideos(ctx context.Context, in *AdminListVideosRequest, opts ...grpc.CallOption) (*AdminListVideosReply, error)
	AdminDeleteVideo(ctx context.Context, in *AdminDeleteVideoRequest, opts ...grpc.CallOption) (*AdminDeleteVideoReply, error)
	AdminCreateTag(ctx context.Context, in *AdminCreateTagRequest, opts ...grpc.CallOption) (*AdminCreateTagReply, error)
	AdminUpdateTag(ctx context.Context, in *AdminUpdateTagRequest, opts ...grpc.CallOption) (*AdminUpdateTagReply, error)
	AdminDeleteTag(ctx context.Context, in *AdminDeleteTagRequest, opts ...grpc.CallOption) (*AdminDeleteTagReply, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) AdminListUsers(ctx context.Context, in *AdminListUsersRequest, opts ...grpc.CallOption) (*AdminListUsersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListUsersReply)
	err := c.cc.Invoke(ctx, AdminService_AdminListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AdminDeleteUser(ctx context.Context, in *AdminDeleteUserRequest, opts ...grpc.CallOption) (*AdminDeleteUserReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDeleteUserReply)
	err := c.cc.Invoke(ctx, AdminService_AdminDeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AdminListVideos(ctx context.Context, in *AdminListVideosRequest, opts ...grpc.CallOption) (*AdminListVideosReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListVideosReply)
	err := c.cc.Invoke(ctx, AdminService_AdminListVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AdminDeleteVideo(ctx context.Context, in *AdminDeleteVideoRequest, opts ...grpc.CallOption) (*AdminDeleteVideoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDeleteVideoReply)
	err := c.cc.Invoke(ctx, AdminService_AdminDeleteVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AdminCreateTag(ctx context.Context, in *AdminCreateTagRequest, opts ...grpc.CallOption) (*AdminCreateTagReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminCreateTagReply)
	err := c.cc.Invoke(ctx, AdminService_AdminCreateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AdminUpdateTag(ctx context.Context, in *AdminUpdateTagRequest, opts ...grpc.CallOption) (*AdminUpdateTagReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpdateTagReply)
	err := c.cc.Invoke(ctx, AdminService_AdminUpdateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AdminDeleteTag(ctx context.Context, in *AdminDeleteTagRequest, opts ...grpc.CallOption) (*AdminDeleteTagReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDeleteTagReply)
	err := c.cc.Invoke(ctx, AdminService_AdminDeleteTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
type AdminServiceServer interface {
	AdminListUsers(context.Context, *AdminListUsersRequest) (*AdminListUsersReply, error)
	AdminDeleteUser(context.Context, *AdminDeleteUserRequest) (*AdminDeleteUserReply, error)
	AdminListVideos(context.Context, *AdminListVideosRequest) (*AdminListVideosReply, error)
	AdminDeleteVideo(context.Context, *AdminDeleteVideoRequest) (*AdminDeleteVideoReply, error)
	AdminCreateTag(context.Context, *AdminCreateTagRequest) (*AdminCreateTagReply, error)
	AdminUpdateTag(context.Context, *AdminUpdateTagRequest) (*AdminUpdateTagReply, error)
	AdminDeleteTag(context.Context, *AdminDeleteTagRequest) (*AdminDeleteTagReply, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) AdminListUsers(context.Context, *AdminListUsersRequest) (*AdminListUsersReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListUsers not implemented")
}
func (UnimplementedAdminServiceServer) AdminDeleteUser(context.Context, *AdminDeleteUserRequest) (*AdminDeleteUserReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminDeleteUser not implemented")
}
func (UnimplementedAdminServiceServer) AdminListVideos(context.Context, *AdminListVideosRequest) (*AdminListVideosReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListVideos not implemented")
}
func (UnimplementedAdminServiceServer) AdminDeleteVideo(context.Context, *AdminDeleteVideoRequest) (*AdminDeleteVideoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminDeleteVideo not implemented")
}
func (UnimplementedAdminServiceServer) AdminCreateTag(context.Context, *AdminCreateTagRequest) (*AdminCreateTagReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminCreateTag not implemented")
}
func (UnimplementedAdminServiceServer) AdminUpdateTag(context.Context, *AdminUpdateTagRequest) (*AdminUpdateTagReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminUpdateTag not implemented")
}
func (UnimplementedAdminServiceServer) AdminDeleteTag(context.Context, *AdminDeleteTagRequest) (*AdminDeleteTagReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminDeleteTag not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_AdminListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AdminListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_AdminListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AdminListUsers(ctx, req.(*AdminListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AdminDeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AdminDeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_AdminDeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AdminDeleteUser(ctx, req.(*AdminDeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AdminListVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AdminListVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_AdminListVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AdminListVideos(ctx, req.(*AdminListVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AdminDeleteVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeleteVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AdminDeleteVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_AdminDeleteVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AdminDeleteVideo(ctx, req.(*AdminDeleteVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AdminCreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AdminCreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_AdminCreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AdminCreateTag(ctx, req.(*AdminCreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AdminUpdateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AdminUpdateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_AdminUpdateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AdminUpdateTag(ctx, req.(*AdminUpdateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AdminDeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AdminDeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_AdminDeleteTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AdminDeleteTag(ctx, req.(*AdminDeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fenzvideo.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminListUsers",
			Handler:    _AdminService_AdminListUsers_Handler,
		},
		{
			MethodName: "AdminDeleteUser",
			Handler:    _AdminService_AdminDeleteUser_Handler,
		},
		{
			MethodName: "AdminListVideos",
			Handler:    _AdminService_AdminListVideos_Handler,
		},
		{
			MethodName: "AdminDeleteVideo",
			Handler:    _AdminService_AdminDeleteVideo_Handler,
		},
		{
			MethodName: "AdminCreateTag",
			Handler:    _AdminService_AdminCreateTag_Handler,
		},
		{
			MethodName: "AdminUpdateTag",
			Handler:    _AdminService_AdminUpdateTag_Handler,
		},
		{
			MethodName: "AdminDeleteTag",
			Handler:    _AdminService_AdminDeleteTag_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fenzvideo/v1/admin.proto",
}
