// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: fenzvideo/v1/admin.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	IsHidden      bool                   `protobuf:"varint,5,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserInfo) Reset() {
	*x = AdminUserInfo{}
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserInfo) ProtoMessage() {}

func (x *AdminUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserInfo.ProtoReflect.Descriptor instead.
func (*AdminUserInfo) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminUserInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminUserInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AdminUserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AdminUserInfo) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

func (x *AdminUserInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AdminListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListUsersRequest) Reset() {
	*x = AdminListUsersRequest{}
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListUsersRequest) ProtoMessage() {}

func (x *AdminListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListUsersRequest.ProtoReflect.Descriptor instead.
func (*AdminListUsersRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AdminListUsersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*AdminUserInfo       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListUsersReply) Reset() {
	*x = AdminListUsersReply{}
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListUsersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListUsersReply) ProtoMessage() {}

func (x *AdminListUsersReply) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListUsersReply.ProtoReflect.Descriptor instead.
func (*AdminListUsersReply) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminListUsersReply) GetUsers() []*AdminUserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *AdminListUsersReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AdminDeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteUserRequest) Reset() {
	*x = AdminDeleteUserRequest{}
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteUserRequest) ProtoMessage() {}

func (x *AdminDeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteUserRequest.ProtoReflect.Descriptor instead.
func (*AdminDeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AdminDeleteUserRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminDeleteUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteUserReply) Reset() {
	*x = AdminDeleteUserReply{}
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteUserReply) ProtoMessage() {}

func (x *AdminDeleteUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteUserReply.ProtoReflect.Descriptor instead.
func (*AdminDeleteUserReply) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_admin_proto_rawDescGZIP(), []int{4}
}

type AdminVideoInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Username       string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	UserId         uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CategoryName   string                 `protobuf:"bytes,5,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	AccessTier     int32                  `protobuf:"varint,6,opt,name=access_tier,json=accessTier,proto3" json:"access_tier,omitempty"`
	IsPublished    bool                   `protobuf:"varint,7,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	IsHidden       bool                   `protobuf:"varint,8,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`
	ViewsMember    uint64                 `protobuf:"varint,9,opt,name=views_member,json=viewsMember,proto3" json:"views_member,omitempty"`
	ViewsNonMember uint64                 `protobuf:"varint,10,opt,name=views_non_member,json=viewsNonMember,proto3" json:"views_non_member,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminVideoInfo) Reset() {
	*x = AdminVideoInfo{}
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminVideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminVideoInfo) ProtoMessage() {}

func (x *AdminVideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminVideoInfo.ProtoReflect.Descriptor instead.
func (*AdminVideoInfo) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *AdminVideoInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminVideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AdminVideoInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminVideoInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdminVideoInfo) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *AdminVideoInfo) GetAccessTier() int32 {
	if x != nil {
		return x.AccessTier
	}
	return 0
}

func (x *AdminVideoInfo) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *AdminVideoInfo) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

func (x *AdminVideoInfo) GetViewsMember() uint64 {
	if x != nil {
		return x.ViewsMember
	}
	return 0
}

func (x *AdminVideoInfo) GetViewsNonMember() uint64 {
	if x != nil {
		return x.ViewsNonMember
	}
	return 0
}

func (x *AdminVideoInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AdminListVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListVideosRequest) Reset() {
	*x = AdminListVideosRequest{}
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListVideosRequest) ProtoMessage() {}

func (x *AdminListVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListVideosRequest.ProtoReflect.Descriptor instead.
func (*AdminListVideosRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *AdminListVideosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminListVideosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AdminListVideosReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*AdminVideoInfo      `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListVideosReply) Reset() {
	*x = AdminListVideosReply{}
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListVideosReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListVideosReply) ProtoMessage() {}

func (x *AdminListVideosReply) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListVideosReply.ProtoReflect.Descriptor instead.
func (*AdminListVideosReply) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *AdminListVideosReply) GetVideos() []*AdminVideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *AdminListVideosReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AdminDeleteVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteVideoRequest) Reset() {
	*x = AdminDeleteVideoRequest{}
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteVideoRequest) ProtoMessage() {}

func (x *AdminDeleteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteVideoRequest.ProtoReflect.Descriptor instead.
func (*AdminDeleteVideoRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *AdminDeleteVideoRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminDeleteVideoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteVideoReply) Reset() {
	*x = AdminDeleteVideoReply{}
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteVideoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteVideoReply) ProtoMessage() {}

func (x *AdminDeleteVideoReply) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteVideoReply.ProtoReflect.Descriptor instead.
func (*AdminDeleteVideoReply) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_admin_proto_rawDescGZIP(), []int{9}
}

type AdminTagInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminTagInfo) Reset() {
	*x = AdminTagInfo{}
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminTagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminTagInfo) ProtoMessage() {}

func (x *AdminTagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminTagInfo.ProtoReflect.Descriptor instead.
func (*AdminTagInfo) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *AdminTagInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminTagInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminTagInfo) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type AdminCreateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminCreateTagRequest) Reset() {
	*x = AdminCreateTagRequest{}
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminCreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCreateTagRequest) ProtoMessage() {}

func (x *AdminCreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCreateTagRequest.ProtoReflect.Descriptor instead.
func (*AdminCreateTagRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *AdminCreateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminCreateTagRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type AdminCreateTagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *AdminTagInfo          `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminCreateTagReply) Reset() {
	*x = AdminCreateTagReply{}
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminCreateTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCreateTagReply) ProtoMessage() {}

func (x *AdminCreateTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCreateTagReply.ProtoReflect.Descriptor instead.
func (*AdminCreateTagReply) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *AdminCreateTagReply) GetTag() *AdminTagInfo {
	if x != nil {
		return x.Tag
	}
	return nil
}

type AdminUpdateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateTagRequest) Reset() {
	*x = AdminUpdateTagRequest{}
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateTagRequest) ProtoMessage() {}

func (x *AdminUpdateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateTagRequest.ProtoReflect.Descriptor instead.
func (*AdminUpdateTagRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *AdminUpdateTagRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUpdateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminUpdateTagRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type AdminUpdateTagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *AdminTagInfo          `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateTagReply) Reset() {
	*x = AdminUpdateTagReply{}
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateTagReply) ProtoMessage() {}

func (x *AdminUpdateTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateTagReply.ProtoReflect.Descriptor instead.
func (*AdminUpdateTagReply) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *AdminUpdateTagReply) GetTag() *AdminTagInfo {
	if x != nil {
		return x.Tag
	}
	return nil
}

type AdminDeleteTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteTagRequest) Reset() {
	*x = AdminDeleteTagRequest{}
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteTagRequest) ProtoMessage() {}

func (x *AdminDeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteTagRequest.ProtoReflect.Descriptor instead.
func (*AdminDeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *AdminDeleteTagRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminDeleteTagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteTagReply) Reset() {
	*x = AdminDeleteTagReply{}
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteTagReply) ProtoMessage() {}

func (x *AdminDeleteTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteTagReply.ProtoReflect.Descriptor instead.
func (*AdminDeleteTagReply) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_admin_proto_rawDescGZIP(), []int{16}
}

var File_fenzvideo_v1_admin_proto protoreflect.FileDescriptor

const file_fenzvideo_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x18fenzvideo/v1/admin.proto\x12\ffenzvideo.v1\x1a\x1cgoogle/api/annotations.proto\"\xae\x01\n" +
	"\rAdminUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1b\n" +
	"\tis_hidden\x18\x05 \x01(\bR\bisHidden\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"H\n" +
	"\x15AdminListUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"^\n" +
	"\x13AdminListUsersReply\x121\n" +
	"\x05users\x18\x01 \x03(\v2\x1b.fenzvideo.v1.AdminUserInfoR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"(\n" +
	"\x16AdminDeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x16\n" +
	"\x14AdminDeleteUserReply\"\xdd\x02\n" +
	"\x0eAdminVideoInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12#\n" +
	"\rcategory_name\x18\x05 \x01(\tR\fcategoryName\x12\x1f\n" +
	"\vaccess_tier\x18\x06 \x01(\x05R\n" +
	"accessTier\x12!\n" +
	"\fis_published\x18\a \x01(\bR\visPublished\x12\x1b\n" +
	"\tis_hidden\x18\b \x01(\bR\bisHidden\x12!\n" +
	"\fviews_member\x18\t \x01(\x04R\vviewsMember\x12(\n" +
	"\x10views_non_member\x18\n" +
	" \x01(\x04R\x0eviewsNonMember\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\"I\n" +
	"\x16AdminListVideosRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"b\n" +
	"\x14AdminListVideosReply\x124\n" +
	"\x06videos\x18\x01 \x03(\v2\x1c.fenzvideo.v1.AdminVideoInfoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\")\n" +
	"\x17AdminDeleteVideoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x17\n" +
	"\x15AdminDeleteVideoReply\"F\n" +
	"\fAdminTagInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\"?\n" +
	"\x15AdminCreateTagRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"C\n" +
	"\x13AdminCreateTagReply\x12,\n" +
	"\x03tag\x18\x01 \x01(\v2\x1a.fenzvideo.v1.AdminTagInfoR\x03tag\"O\n" +
	"\x15AdminUpdateTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\"C\n" +
	"\x13AdminUpdateTagReply\x12,\n" +
	"\x03tag\x18\x01 \x01(\v2\x1a.fenzvideo.v1.AdminTagInfoR\x03tag\"'\n" +
	"\x15AdminDeleteTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x15\n" +
	"\x13AdminDeleteTagReply2\xf5\x06\n" +
	"\fAdminService\x12u\n" +
	"\x0eAdminListUsers\x12#.fenzvideo.v1.AdminListUsersRequest\x1a!.fenzvideo.v1.AdminListUsersReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/admin/users\x12}\n" +
	"\x0fAdminDeleteUser\x12$.fenzvideo.v1.AdminDeleteUserRequest\x1a\".fenzvideo.v1.AdminDeleteUserReply\" \x82\xd3\xe4\x93\x02\x1a*\x18/api/v1/admin/users/{id}\x12y\n" +
	"\x0fAdminListVideos\x12$.fenzvideo.v1.AdminListVideosRequest\x1a\".fenzvideo.v1.AdminListVideosReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/admin/videos\x12\x81\x01\n" +
	"\x10AdminDeleteVideo\x12%.fenzvideo.v1.AdminDeleteVideoRequest\x1a#.fenzvideo.v1.AdminDeleteVideoReply\"!\x82\xd3\xe4\x93\x02\x1b*\x19/api/v1/admin/videos/{id}\x12w\n" +
	"\x0eAdminCreateTag\x12#.fenzvideo.v1.AdminCreateTagRequest\x1a!.fenzvideo.v1.AdminCreateTagReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/admin/tags\x12|\n" +
	"\x0eAdminUpdateTag\x12#.fenzvideo.v1.AdminUpdateTagRequest\x1a!.fenzvideo.v1.AdminUpdateTagReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/api/v1/admin/tags/{id}\x12y\n" +
	"\x0eAdminDeleteTag\x12#.fenzvideo.v1.AdminDeleteTagRequest\x1a!.fenzvideo.v1.AdminDeleteTagReply\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/api/v1/admin/tags/{id}B\x1dZ\x1bbackend/api/fenzvideo/v1;v1b\x06proto3"

var (
	file_fenzvideo_v1_admin_proto_rawDescOnce sync.Once
	file_fenzvideo_v1_admin_proto_rawDescData []byte
)

func file_fenzvideo_v1_admin_proto_rawDescGZIP() []byte {
	file_fenzvideo_v1_admin_proto_rawDescOnce.Do(func() {
		file_fenzvideo_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fenzvideo_v1_admin_proto_rawDesc), len(file_fenzvideo_v1_admin_proto_rawDesc)))
	})
	return file_fenzvideo_v1_admin_proto_rawDescData
}

var file_fenzvideo_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_fenzvideo_v1_admin_proto_goTypes = []any{
	(*AdminUserInfo)(nil),           // 0: fenzvideo.v1.AdminUserInfo
	(*AdminListUsersRequest)(nil),   // 1: fenzvideo.v1.AdminListUsersRequest
	(*AdminListUsersReply)(nil),     // 2: fenzvideo.v1.AdminListUsersReply
	(*AdminDeleteUserRequest)(nil),  // 3: fenzvideo.v1.AdminDeleteUserRequest
	(*AdminDeleteUserReply)(nil),    // 4: fenzvideo.v1.AdminDeleteUserReply
	(*AdminVideoInfo)(nil),          // 5: fenzvideo.v1.AdminVideoInfo
	(*AdminListVideosRequest)(nil),  // 6: fenzvideo.v1.AdminListVideosRequest
	(*AdminListVideosReply)(nil),    // 7: fenzvideo.v1.AdminListVideosReply
	(*AdminDeleteVideoRequest)(nil), // 8: fenzvideo.v1.AdminDeleteVideoRequest
	(*AdminDeleteVideoReply)(nil),   // 9: fenzvideo.v1.AdminDeleteVideoReply
	(*AdminTagInfo)(nil),            // 10: fenzvideo.v1.AdminTagInfo
	(*AdminCreateTagRequest)(nil),   // 11: fenzvideo.v1.AdminCreateTagRequest
	(*AdminCreateTagReply)(nil),     // 12: fenzvideo.v1.AdminCreateTagReply
	(*AdminUpdateTagRequest)(nil),   // 13: fenzvideo.v1.AdminUpdateTagRequest
	(*AdminUpdateTagReply)(nil),     // 14: fenzvideo.v1.AdminUpdateTagReply
	(*AdminDeleteTagRequest)(nil),   // 15: fenzvideo.v1.AdminDeleteTagRequest
	(*AdminDeleteTagReply)(nil),     // 16: fenzvideo.v1.AdminDeleteTagReply
}
var file_fenzvideo_v1_admin_proto_depIdxs = []int32{
	0,  // 0: fenzvideo.v1.AdminListUsersReply.users:type_name -> fenzvideo.v1.AdminUserInfo
	5,  // 1: fenzvideo.v1.AdminListVideosReply.videos:type_name -> fenzvideo.v1.AdminVideoInfo
	10, // 2: fenzvideo.v1.AdminCreateTagReply.tag:type_name -> fenzvideo.v1.AdminTagInfo
	10, // 3: fenzvideo.v1.AdminUpdateTagReply.tag:type_name -> fenzvideo.v1.AdminTagInfo
	1,  // 4: fenzvideo.v1.AdminService.AdminListUsers:input_type -> fenzvideo.v1.AdminListUsersRequest
	3,  // 5: fenzvideo.v1.AdminService.AdminDeleteUser:input_type -> fenzvideo.v1.AdminDeleteUserRequest
	6,  // 6: fenzvideo.v1.AdminService.AdminListVideos:input_type -> fenzvideo.v1.AdminListVideosRequest
	8,  // 7: fenzvideo.v1.AdminService.AdminDeleteVideo:input_type -> fenzvideo.v1.AdminDeleteVideoRequest
	11, // 8: fenzvideo.v1.AdminService.AdminCreateTag:input_type -> fenzvideo.v1.AdminCreateTagRequest
	13, // 9: fenzvideo.v1.AdminService.AdminUpdateTag:input_type -> fenzvideo.v1.AdminUpdateTagRequest
	15, // 10: fenzvideo.v1.AdminService.AdminDeleteTag:input_type -> fenzvideo.v1.AdminDeleteTagRequest
	2,  // 11: fenzvideo.v1.AdminService.AdminListUsers:output_type -> fenzvideo.v1.AdminListUsersReply
	4,  // 12: fenzvideo.v1.AdminService.AdminDeleteUser:output_type -> fenzvideo.v1.AdminDeleteUserReply
	7,  // 13: fenzvideo.v1.AdminService.AdminListVideos:output_type -> fenzvideo.v1.AdminListVideosReply
	9,  // 14: fenzvideo.v1.AdminService.AdminDeleteVideo:output_type -> fenzvideo.v1.AdminDeleteVideoReply
	12, // 15: fenzvideo.v1.AdminService.AdminCreateTag:output_type -> fenzvideo.v1.AdminCreateTagReply
	14, // 16: fenzvideo.v1.AdminService.AdminUpdateTag:output_type -> fenzvideo.v1.AdminUpdateTagReply
	16, // 17: fenzvideo.v1.AdminService.AdminDeleteTag:output_type -> fenzvideo.v1.AdminDeleteTagReply
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_fenzvideo_v1_admin_proto_init() }
func file_fenzvideo_v1_admin_proto_init() {
	if File_fenzvideo_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fenzvideo_v1_admin_proto_rawDesc), len(file_fenzvideo_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fenzvideo_v1_admin_proto_goTypes,
		DependencyIndexes: file_fenzvideo_v1_admin_proto_depIdxs,
		MessageInfos:      file_fenzvideo_v1_admin_proto_msgTypes,
	}.Build()
	File_fenzvideo_v1_admin_proto = out.File
	file_fenzvideo_v1_admin_proto_goTypes = nil
	file_fenzvideo_v1_admin_proto_depIdxs = nil
}
