// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: fenzvideo/v1/category.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_fenzvideo_v1_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_category_proto_rawDescGZIP(), []int{0}
}

type ListCategoriesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CategoryItem        `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesReply) Reset() {
	*x = ListCategoriesReply{}
	mi := &file_fenzvideo_v1_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesReply) ProtoMessage() {}

func (x *ListCategoriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesReply.ProtoReflect.Descriptor instead.
func (*ListCategoriesReply) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_category_proto_rawDescGZIP(), []int{1}
}

func (x *ListCategoriesReply) GetCategories() []*CategoryItem {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CategoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryItem) Reset() {
	*x = CategoryItem{}
	mi := &file_fenzvideo_v1_category_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryItem) ProtoMessage() {}

func (x *CategoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_category_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryItem.ProtoReflect.Descriptor instead.
func (*CategoryItem) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_category_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryItem) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

var File_fenzvideo_v1_category_proto protoreflect.FileDescriptor

const file_fenzvideo_v1_category_proto_rawDesc = "" +
	"\n" +
	"\x1bfenzvideo/v1/category.proto\x12\ffenzvideo.v1\x1a\x1cgoogle/api/annotations.proto\"\x17\n" +
	"\x15ListCategoriesRequest\"Q\n" +
	"\x13ListCategoriesReply\x12:\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1a.fenzvideo.v1.CategoryItemR\n" +
	"categories\"F\n" +
	"\fCategoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug2\x87\x01\n" +
	"\x0fCategoryService\x12t\n" +
	"\x0eListCategories\x12#.fenzvideo.v1.ListCategoriesRequest\x1a!.fenzvideo.v1.ListCategoriesReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/categoriesB\x1dZ\x1bbackend/api/fenzvideo/v1;v1b\x06proto3"

var (
	file_fenzvideo_v1_category_proto_rawDescOnce sync.Once
	file_fenzvideo_v1_category_proto_rawDescData []byte
)

func file_fenzvideo_v1_category_proto_rawDescGZIP() []byte {
	file_fenzvideo_v1_category_proto_rawDescOnce.Do(func() {
		file_fenzvideo_v1_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fenzvideo_v1_category_proto_rawDesc), len(file_fenzvideo_v1_category_proto_rawDesc)))
	})
	return file_fenzvideo_v1_category_proto_rawDescData
}

var file_fenzvideo_v1_category_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_fenzvideo_v1_category_proto_goTypes = []any{
	(*ListCategoriesRequest)(nil), // 0: fenzvideo.v1.ListCategoriesRequest
	(*ListCategoriesReply)(nil),   // 1: fenzvideo.v1.ListCategoriesReply
	(*CategoryItem)(nil),          // 2: fenzvideo.v1.CategoryItem
}
var file_fenzvideo_v1_category_proto_depIdxs = []int32{
	2, // 0: fenzvideo.v1.ListCategoriesReply.categories:type_name -> fenzvideo.v1.CategoryItem
	0, // 1: fenzvideo.v1.CategoryService.ListCategories:input_type -> fenzvideo.v1.ListCategoriesRequest
	1, // 2: fenzvideo.v1.CategoryService.ListCategories:output_type -> fenzvideo.v1.ListCategoriesReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fenzvideo_v1_category_proto_init() }
func file_fenzvideo_v1_category_proto_init() {
	if File_fenzvideo_v1_category_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fenzvideo_v1_category_proto_rawDesc), len(file_fenzvideo_v1_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fenzvideo_v1_category_proto_goTypes,
		DependencyIndexes: file_fenzvideo_v1_category_proto_depIdxs,
		MessageInfos:      file_fenzvideo_v1_category_proto_msgTypes,
	}.Build()
	File_fenzvideo_v1_category_proto = out.File
	file_fenzvideo_v1_category_proto_goTypes = nil
	file_fenzvideo_v1_category_proto_depIdxs = nil
}
