// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: fenzvideo/v1/channel.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelRequest) Reset() {
	*x = GetChannelRequest{}
	mi := &file_fenzvideo_v1_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelRequest) ProtoMessage() {}

func (x *GetChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelRequest.ProtoReflect.Descriptor instead.
func (*GetChannelRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_channel_proto_rawDescGZIP(), []int{0}
}

func (x *GetChannelRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ChannelReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName      string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl        string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	MonthlyFee       float64                `protobuf:"fixed64,5,opt,name=monthly_fee,json=monthlyFee,proto3" json:"monthly_fee,omitempty"`
	SubscriberCount  int64                  `protobuf:"varint,6,opt,name=subscriber_count,json=subscriberCount,proto3" json:"subscriber_count,omitempty"`
	MembershipStatus string                 `protobuf:"bytes,7,opt,name=membership_status,json=membershipStatus,proto3" json:"membership_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChannelReply) Reset() {
	*x = ChannelReply{}
	mi := &file_fenzvideo_v1_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelReply) ProtoMessage() {}

func (x *ChannelReply) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelReply.ProtoReflect.Descriptor instead.
func (*ChannelReply) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_channel_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChannelReply) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChannelReply) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ChannelReply) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *ChannelReply) GetMonthlyFee() float64 {
	if x != nil {
		return x.MonthlyFee
	}
	return 0
}

func (x *ChannelReply) GetSubscriberCount() int64 {
	if x != nil {
		return x.SubscriberCount
	}
	return 0
}

func (x *ChannelReply) GetMembershipStatus() string {
	if x != nil {
		return x.MembershipStatus
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_fenzvideo_v1_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_channel_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MembershipReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Tier          string                 `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipReply) Reset() {
	*x = MembershipReply{}
	mi := &file_fenzvideo_v1_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipReply) ProtoMessage() {}

func (x *MembershipReply) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipReply.ProtoReflect.Descriptor instead.
func (*MembershipReply) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_channel_proto_rawDescGZIP(), []int{3}
}

func (x *MembershipReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MembershipReply) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_fenzvideo_v1_channel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_channel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_channel_proto_rawDescGZIP(), []int{4}
}

func (x *UnsubscribeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UnsubscribeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeReply) Reset() {
	*x = UnsubscribeReply{}
	mi := &file_fenzvideo_v1_channel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeReply) ProtoMessage() {}

func (x *UnsubscribeReply) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_channel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeReply.ProtoReflect.Descriptor instead.
func (*UnsubscribeReply) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_channel_proto_rawDescGZIP(), []int{5}
}

func (x *UnsubscribeReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_fenzvideo_v1_channel_proto protoreflect.FileDescriptor

const file_fenzvideo_v1_channel_proto_rawDesc = "" +
	"\n" +
	"\x1afenzvideo/v1/channel.proto\x12\ffenzvideo.v1\x1a\x1cgoogle/api/annotations.proto\"#\n" +
	"\x11GetChannelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xf2\x01\n" +
	"\fChannelReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x1f\n" +
	"\vmonthly_fee\x18\x05 \x01(\x01R\n" +
	"monthlyFee\x12)\n" +
	"\x10subscriber_count\x18\x06 \x01(\x03R\x0fsubscriberCount\x12+\n" +
	"\x11membership_status\x18\a \x01(\tR\x10membershipStatus\"\"\n" +
	"\x10SubscribeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"=\n" +
	"\x0fMembershipReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\tR\x04tier\"$\n" +
	"\x12UnsubscribeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"*\n" +
	"\x10UnsubscribeReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xec\x02\n" +
	"\x0eChannelService\x12h\n" +
	"\n" +
	"GetChannel\x12\x1f.fenzvideo.v1.GetChannelRequest\x1a\x1a.fenzvideo.v1.ChannelReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/channels/{id}\x12v\n" +
	"\tSubscribe\x12\x1e.fenzvideo.v1.SubscribeRequest\x1a\x1d.fenzvideo.v1.MembershipReply\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/channels/{id}/subscribe\x12x\n" +
	"\vUnsubscribe\x12 .fenzvideo.v1.UnsubscribeRequest\x1a\x1e.fenzvideo.v1.UnsubscribeReply\"'\x82\xd3\xe4\x93\x02!*\x1f/api/v1/channels/{id}/subscribeB\x1dZ\x1bbackend/api/fenzvideo/v1;v1b\x06proto3"

var (
	file_fenzvideo_v1_channel_proto_rawDescOnce sync.Once
	file_fenzvideo_v1_channel_proto_rawDescData []byte
)

func file_fenzvideo_v1_channel_proto_rawDescGZIP() []byte {
	file_fenzvideo_v1_channel_proto_rawDescOnce.Do(func() {
		file_fenzvideo_v1_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fenzvideo_v1_channel_proto_rawDesc), len(file_fenzvideo_v1_channel_proto_rawDesc)))
	})
	return file_fenzvideo_v1_channel_proto_rawDescData
}

var file_fenzvideo_v1_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_fenzvideo_v1_channel_proto_goTypes = []any{
	(*GetChannelRequest)(nil),  // 0: fenzvideo.v1.GetChannelRequest
	(*ChannelReply)(nil),       // 1: fenzvideo.v1.ChannelReply
	(*SubscribeRequest)(nil),   // 2: fenzvideo.v1.SubscribeRequest
	(*MembershipReply)(nil),    // 3: fenzvideo.v1.MembershipReply
	(*UnsubscribeRequest)(nil), // 4: fenzvideo.v1.UnsubscribeRequest
	(*UnsubscribeReply)(nil),   // 5: fenzvideo.v1.UnsubscribeReply
}
var file_fenzvideo_v1_channel_proto_depIdxs = []int32{
	0, // 0: fenzvideo.v1.ChannelService.GetChannel:input_type -> fenzvideo.v1.GetChannelRequest
	2, // 1: fenzvideo.v1.ChannelService.Subscribe:input_type -> fenzvideo.v1.SubscribeRequest
	4, // 2: fenzvideo.v1.ChannelService.Unsubscribe:input_type -> fenzvideo.v1.UnsubscribeRequest
	1, // 3: fenzvideo.v1.ChannelService.GetChannel:output_type -> fenzvideo.v1.ChannelReply
	3, // 4: fenzvideo.v1.ChannelService.Subscribe:output_type -> fenzvideo.v1.MembershipReply
	5, // 5: fenzvideo.v1.ChannelService.Unsubscribe:output_type -> fenzvideo.v1.UnsubscribeReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fenzvideo_v1_channel_proto_init() }
func file_fenzvideo_v1_channel_proto_init() {
	if File_fenzvideo_v1_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fenzvideo_v1_channel_proto_rawDesc), len(file_fenzvideo_v1_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fenzvideo_v1_channel_proto_goTypes,
		DependencyIndexes: file_fenzvideo_v1_channel_proto_depIdxs,
		MessageInfos:      file_fenzvideo_v1_channel_proto_msgTypes,
	}.Build()
	File_fenzvideo_v1_channel_proto = out.File
	file_fenzvideo_v1_channel_proto_goTypes = nil
	file_fenzvideo_v1_channel_proto_depIdxs = nil
}
