// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: fenzvideo/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// Common
	ErrorReason_ERROR_REASON_UNSPECIFIED ErrorReason = 0
	// Auth
	ErrorReason_INVALID_CREDENTIALS     ErrorReason = 1
	ErrorReason_USERNAME_ALREADY_EXISTS ErrorReason = 2
	ErrorReason_TOKEN_EXPIRED           ErrorReason = 3
	ErrorReason_TOKEN_INVALID           ErrorReason = 4
	ErrorReason_UNAUTHORIZED            ErrorReason = 5
	ErrorReason_ACCOUNT_HIDDEN          ErrorReason = 6
	// Admin
	ErrorReason_ADMIN_REQUIRED    ErrorReason = 7
	ErrorReason_ADMIN_SELF_DELETE ErrorReason = 8
	// User
	ErrorReason_USER_NOT_FOUND    ErrorReason = 9
	ErrorReason_PASSWORD_MISMATCH ErrorReason = 10
	// Video
	ErrorReason_VIDEO_NOT_FOUND     ErrorReason = 11
	ErrorReason_VIDEO_ACCESS_DENIED ErrorReason = 12
	ErrorReason_VIDEO_NOT_OWNER     ErrorReason = 13
	ErrorReason_VIDEO_UPLOAD_FAILED ErrorReason = 14
	// Channel
	ErrorReason_CHANNEL_NOT_FOUND          ErrorReason = 15
	ErrorReason_CHANNEL_ALREADY_SUBSCRIBED ErrorReason = 16
	ErrorReason_CHANNEL_NOT_SUBSCRIBED     ErrorReason = 17
	ErrorReason_CHANNEL_SELF_SUBSCRIBE     ErrorReason = 18
	// Tag
	ErrorReason_TAG_NOT_FOUND      ErrorReason = 19
	ErrorReason_TAG_LIMIT_EXCEEDED ErrorReason = 20
	ErrorReason_TAG_ALREADY_EXISTS ErrorReason = 21
	// Category
	ErrorReason_CATEGORY_NOT_FOUND ErrorReason = 22
	// Membership
	ErrorReason_MEMBERSHIP_NOT_FOUND ErrorReason = 23
	ErrorReason_ALREADY_PREMIUM      ErrorReason = 24
	ErrorReason_NOT_PREMIUM          ErrorReason = 25
	// Donation
	ErrorReason_DONATION_FAILED ErrorReason = 26
	ErrorReason_DONATION_SELF   ErrorReason = 27
	// Notification
	ErrorReason_NOTIFICATION_NOT_FOUND ErrorReason = 28
	// Paddle
	ErrorReason_PADDLE_WEBHOOK_INVALID ErrorReason = 29
	ErrorReason_PADDLE_API_ERROR       ErrorReason = 30
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "ERROR_REASON_UNSPECIFIED",
		1:  "INVALID_CREDENTIALS",
		2:  "USERNAME_ALREADY_EXISTS",
		3:  "TOKEN_EXPIRED",
		4:  "TOKEN_INVALID",
		5:  "UNAUTHORIZED",
		6:  "ACCOUNT_HIDDEN",
		7:  "ADMIN_REQUIRED",
		8:  "ADMIN_SELF_DELETE",
		9:  "USER_NOT_FOUND",
		10: "PASSWORD_MISMATCH",
		11: "VIDEO_NOT_FOUND",
		12: "VIDEO_ACCESS_DENIED",
		13: "VIDEO_NOT_OWNER",
		14: "VIDEO_UPLOAD_FAILED",
		15: "CHANNEL_NOT_FOUND",
		16: "CHANNEL_ALREADY_SUBSCRIBED",
		17: "CHANNEL_NOT_SUBSCRIBED",
		18: "CHANNEL_SELF_SUBSCRIBE",
		19: "TAG_NOT_FOUND",
		20: "TAG_LIMIT_EXCEEDED",
		21: "TAG_ALREADY_EXISTS",
		22: "CATEGORY_NOT_FOUND",
		23: "MEMBERSHIP_NOT_FOUND",
		24: "ALREADY_PREMIUM",
		25: "NOT_PREMIUM",
		26: "DONATION_FAILED",
		27: "DONATION_SELF",
		28: "NOTIFICATION_NOT_FOUND",
		29: "PADDLE_WEBHOOK_INVALID",
		30: "PADDLE_API_ERROR",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED":   0,
		"INVALID_CREDENTIALS":        1,
		"USERNAME_ALREADY_EXISTS":    2,
		"TOKEN_EXPIRED":              3,
		"TOKEN_INVALID":              4,
		"UNAUTHORIZED":               5,
		"ACCOUNT_HIDDEN":             6,
		"ADMIN_REQUIRED":             7,
		"ADMIN_SELF_DELETE":          8,
		"USER_NOT_FOUND":             9,
		"PASSWORD_MISMATCH":          10,
		"VIDEO_NOT_FOUND":            11,
		"VIDEO_ACCESS_DENIED":        12,
		"VIDEO_NOT_OWNER":            13,
		"VIDEO_UPLOAD_FAILED":        14,
		"CHANNEL_NOT_FOUND":          15,
		"CHANNEL_ALREADY_SUBSCRIBED": 16,
		"CHANNEL_NOT_SUBSCRIBED":     17,
		"CHANNEL_SELF_SUBSCRIBE":     18,
		"TAG_NOT_FOUND":              19,
		"TAG_LIMIT_EXCEEDED":         20,
		"TAG_ALREADY_EXISTS":         21,
		"CATEGORY_NOT_FOUND":         22,
		"MEMBERSHIP_NOT_FOUND":       23,
		"ALREADY_PREMIUM":            24,
		"NOT_PREMIUM":                25,
		"DONATION_FAILED":            26,
		"DONATION_SELF":              27,
		"NOTIFICATION_NOT_FOUND":     28,
		"PADDLE_WEBHOOK_INVALID":     29,
		"PADDLE_API_ERROR":           30,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_fenzvideo_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_fenzvideo_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_fenzvideo_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_fenzvideo_v1_error_reason_proto protoreflect.FileDescriptor

const file_fenzvideo_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1ffenzvideo/v1/error_reason.proto\x12\ffenzvideo.v1*\xdf\x05\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13INVALID_CREDENTIALS\x10\x01\x12\x1b\n" +
	"\x17USERNAME_ALREADY_EXISTS\x10\x02\x12\x11\n" +
	"\rTOKEN_EXPIRED\x10\x03\x12\x11\n" +
	"\rTOKEN_INVALID\x10\x04\x12\x10\n" +
	"\fUNAUTHORIZED\x10\x05\x12\x12\n" +
	"\x0eACCOUNT_HIDDEN\x10\x06\x12\x12\n" +
	"\x0eADMIN_REQUIRED\x10\a\x12\x15\n" +
	"\x11ADMIN_SELF_DELETE\x10\b\x12\x12\n" +
	"\x0eUSER_NOT_FOUND\x10\t\x12\x15\n" +
	"\x11PASSWORD_MISMATCH\x10\n" +
	"\x12\x13\n" +
	"\x0fVIDEO_NOT_FOUND\x10\v\x12\x17\n" +
	"\x13VIDEO_ACCESS_DENIED\x10\f\x12\x13\n" +
	"\x0fVIDEO_NOT_OWNER\x10\r\x12\x17\n" +
	"\x13VIDEO_UPLOAD_FAILED\x10\x0e\x12\x15\n" +
	"\x11CHANNEL_NOT_FOUND\x10\x0f\x12\x1e\n" +
	"\x1aCHANNEL_ALREADY_SUBSCRIBED\x10\x10\x12\x1a\n" +
	"\x16CHANNEL_NOT_SUBSCRIBED\x10\x11\x12\x1a\n" +
	"\x16CHANNEL_SELF_SUBSCRIBE\x10\x12\x12\x11\n" +
	"\rTAG_NOT_FOUND\x10\x13\x12\x16\n" +
	"\x12TAG_LIMIT_EXCEEDED\x10\x14\x12\x16\n" +
	"\x12TAG_ALREADY_EXISTS\x10\x15\x12\x16\n" +
	"\x12CATEGORY_NOT_FOUND\x10\x16\x12\x18\n" +
	"\x14MEMBERSHIP_NOT_FOUND\x10\x17\x12\x13\n" +
	"\x0fALREADY_PREMIUM\x10\x18\x12\x0f\n" +
	"\vNOT_PREMIUM\x10\x19\x12\x13\n" +
	"\x0fDONATION_FAILED\x10\x1a\x12\x11\n" +
	"\rDONATION_SELF\x10\x1b\x12\x1a\n" +
	"\x16NOTIFICATION_NOT_FOUND\x10\x1c\x12\x1a\n" +
	"\x16PADDLE_WEBHOOK_INVALID\x10\x1d\x12\x14\n" +
	"\x10PADDLE_API_ERROR\x10\x1eB\x1dZ\x1bbackend/api/fenzvideo/v1;v1b\x06proto3"

var (
	file_fenzvideo_v1_error_reason_proto_rawDescOnce sync.Once
	file_fenzvideo_v1_error_reason_proto_rawDescData []byte
)

func file_fenzvideo_v1_error_reason_proto_rawDescGZIP() []byte {
	file_fenzvideo_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_fenzvideo_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fenzvideo_v1_error_reason_proto_rawDesc), len(file_fenzvideo_v1_error_reason_proto_rawDesc)))
	})
	return file_fenzvideo_v1_error_reason_proto_rawDescData
}

var file_fenzvideo_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fenzvideo_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: fenzvideo.v1.ErrorReason
}
var file_fenzvideo_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fenzvideo_v1_error_reason_proto_init() }
func file_fenzvideo_v1_error_reason_proto_init() {
	if File_fenzvideo_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fenzvideo_v1_error_reason_proto_rawDesc), len(file_fenzvideo_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fenzvideo_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_fenzvideo_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_fenzvideo_v1_error_reason_proto_enumTypes,
	}.Build()
	File_fenzvideo_v1_error_reason_proto = out.File
	file_fenzvideo_v1_error_reason_proto_goTypes = nil
	file_fenzvideo_v1_error_reason_proto_depIdxs = nil
}
