// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: fenzvideo/v1/search.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	CategoryId    *uint64                `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	MinDuration   *uint32                `protobuf:"varint,3,opt,name=min_duration,json=minDuration,proto3,oneof" json:"min_duration,omitempty"`
	MaxDuration   *uint32                `protobuf:"varint,4,opt,name=max_duration,json=maxDuration,proto3,oneof" json:"max_duration,omitempty"`
	DateFrom      *string                `protobuf:"bytes,5,opt,name=date_from,json=dateFrom,proto3,oneof" json:"date_from,omitempty"`
	DateTo        *string                `protobuf:"bytes,6,opt,name=date_to,json=dateTo,proto3,oneof" json:"date_to,omitempty"`
	SortBy        *string                `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3,oneof" json:"sort_by,omitempty"`
	AccessType    *string                `protobuf:"bytes,8,opt,name=access_type,json=accessType,proto3,oneof" json:"access_type,omitempty"`
	Page          int32                  `protobuf:"varint,9,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_fenzvideo_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetCategoryId() uint64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *SearchRequest) GetMinDuration() uint32 {
	if x != nil && x.MinDuration != nil {
		return *x.MinDuration
	}
	return 0
}

func (x *SearchRequest) GetMaxDuration() uint32 {
	if x != nil && x.MaxDuration != nil {
		return *x.MaxDuration
	}
	return 0
}

func (x *SearchRequest) GetDateFrom() string {
	if x != nil && x.DateFrom != nil {
		return *x.DateFrom
	}
	return ""
}

func (x *SearchRequest) GetDateTo() string {
	if x != nil && x.DateTo != nil {
		return *x.DateTo
	}
	return ""
}

func (x *SearchRequest) GetSortBy() string {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return ""
}

func (x *SearchRequest) GetAccessType() string {
	if x != nil && x.AccessType != nil {
		return *x.AccessType
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_fenzvideo_v1_search_proto protoreflect.FileDescriptor

const file_fenzvideo_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x19fenzvideo/v1/search.proto\x12\ffenzvideo.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x18fenzvideo/v1/video.proto\"\xb8\x03\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12$\n" +
	"\vcategory_id\x18\x02 \x01(\x04H\x00R\n" +
	"categoryId\x88\x01\x01\x12&\n" +
	"\fmin_duration\x18\x03 \x01(\rH\x01R\vminDuration\x88\x01\x01\x12&\n" +
	"\fmax_duration\x18\x04 \x01(\rH\x02R\vmaxDuration\x88\x01\x01\x12 \n" +
	"\tdate_from\x18\x05 \x01(\tH\x03R\bdateFrom\x88\x01\x01\x12\x1c\n" +
	"\adate_to\x18\x06 \x01(\tH\x04R\x06dateTo\x88\x01\x01\x12\x1c\n" +
	"\asort_by\x18\a \x01(\tH\x05R\x06sortBy\x88\x01\x01\x12$\n" +
	"\vaccess_type\x18\b \x01(\tH\x06R\n" +
	"accessType\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\t \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSizeB\x0e\n" +
	"\f_category_idB\x0f\n" +
	"\r_min_durationB\x0f\n" +
	"\r_max_durationB\f\n" +
	"\n" +
	"_date_fromB\n" +
	"\n" +
	"\b_date_toB\n" +
	"\n" +
	"\b_sort_byB\x0e\n" +
	"\f_access_type2l\n" +
	"\rSearchService\x12[\n" +
	"\x06Search\x12\x1b.fenzvideo.v1.SearchRequest\x1a\x1c.fenzvideo.v1.VideoListReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/searchB\x1dZ\x1bbackend/api/fenzvideo/v1;v1b\x06proto3"

var (
	file_fenzvideo_v1_search_proto_rawDescOnce sync.Once
	file_fenzvideo_v1_search_proto_rawDescData []byte
)

func file_fenzvideo_v1_search_proto_rawDescGZIP() []byte {
	file_fenzvideo_v1_search_proto_rawDescOnce.Do(func() {
		file_fenzvideo_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fenzvideo_v1_search_proto_rawDesc), len(file_fenzvideo_v1_search_proto_rawDesc)))
	})
	return file_fenzvideo_v1_search_proto_rawDescData
}

var file_fenzvideo_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fenzvideo_v1_search_proto_goTypes = []any{
	(*SearchRequest)(nil),  // 0: fenzvideo.v1.SearchRequest
	(*VideoListReply)(nil), // 1: fenzvideo.v1.VideoListReply
}
var file_fenzvideo_v1_search_proto_depIdxs = []int32{
	0, // 0: fenzvideo.v1.SearchService.Search:input_type -> fenzvideo.v1.SearchRequest
	1, // 1: fenzvideo.v1.SearchService.Search:output_type -> fenzvideo.v1.VideoListReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fenzvideo_v1_search_proto_init() }
func file_fenzvideo_v1_search_proto_init() {
	if File_fenzvideo_v1_search_proto != nil {
		return
	}
	file_fenzvideo_v1_video_proto_init()
	file_fenzvideo_v1_search_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fenzvideo_v1_search_proto_rawDesc), len(file_fenzvideo_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fenzvideo_v1_search_proto_goTypes,
		DependencyIndexes: file_fenzvideo_v1_search_proto_depIdxs,
		MessageInfos:      file_fenzvideo_v1_search_proto_msgTypes,
	}.Build()
	File_fenzvideo_v1_search_proto = out.File
	file_fenzvideo_v1_search_proto_goTypes = nil
	file_fenzvideo_v1_search_proto_depIdxs = nil
}
