// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.4
// source: fenzvideo/v1/search.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSearchServiceSearch = "/fenzvideo.v1.SearchService/Search"

type SearchServiceHTTPServer interface {
	Search(context.Context, *SearchRequest) (*VideoListReply, error)
}

func RegisterSearchServiceHTTPServer(s *http.Server, srv SearchServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/search", _SearchService_Search0_HTTP_Handler(srv))
}

func _SearchService_Search0_HTTP_Handler(srv SearchServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSearchServiceSearch)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Search(ctx, req.(*SearchRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*VideoListReply)
		return ctx.Result(200, reply)
	}
}

type SearchServiceHTTPClient interface {
	Search(ctx context.Context, req *SearchRequest, opts ...http.CallOption) (rsp *VideoListReply, err error)
}

type SearchServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSearchServiceHTTPClient(client *http.Client) SearchServiceHTTPClient {
	return &SearchServiceHTTPClientImpl{client}
}

func (c *SearchServiceHTTPClientImpl) Search(ctx context.Context, in *SearchRequest, opts ...http.CallOption) (*VideoListReply, error) {
	var out VideoListReply
	pattern := "/api/v1/search"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSearchServiceSearch))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
