// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: fenzvideo/v1/tag.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsRequest) Reset() {
	*x = ListTagsRequest{}
	mi := &file_fenzvideo_v1_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsRequest) ProtoMessage() {}

func (x *ListTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsRequest.ProtoReflect.Descriptor instead.
func (*ListTagsRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_tag_proto_rawDescGZIP(), []int{0}
}

type GetMyTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *string                `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyTagsRequest) Reset() {
	*x = GetMyTagsRequest{}
	mi := &file_fenzvideo_v1_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyTagsRequest) ProtoMessage() {}

func (x *GetMyTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyTagsRequest.ProtoReflect.Descriptor instead.
func (*GetMyTagsRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_tag_proto_rawDescGZIP(), []int{1}
}

func (x *GetMyTagsRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

type SetMyTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagIds        []uint64               `protobuf:"varint,1,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	SessionId     *string                `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMyTagsRequest) Reset() {
	*x = SetMyTagsRequest{}
	mi := &file_fenzvideo_v1_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMyTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMyTagsRequest) ProtoMessage() {}

func (x *SetMyTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMyTagsRequest.ProtoReflect.Descriptor instead.
func (*SetMyTagsRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_tag_proto_rawDescGZIP(), []int{2}
}

func (x *SetMyTagsRequest) GetTagIds() []uint64 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *SetMyTagsRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

type TagListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*TagItem             `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagListReply) Reset() {
	*x = TagListReply{}
	mi := &file_fenzvideo_v1_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagListReply) ProtoMessage() {}

func (x *TagListReply) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagListReply.ProtoReflect.Descriptor instead.
func (*TagListReply) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_tag_proto_rawDescGZIP(), []int{3}
}

func (x *TagListReply) GetTags() []*TagItem {
	if x != nil {
		return x.Tags
	}
	return nil
}

type TagItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagItem) Reset() {
	*x = TagItem{}
	mi := &file_fenzvideo_v1_tag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagItem) ProtoMessage() {}

func (x *TagItem) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_tag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagItem.ProtoReflect.Descriptor instead.
func (*TagItem) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_tag_proto_rawDescGZIP(), []int{4}
}

func (x *TagItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagItem) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

var File_fenzvideo_v1_tag_proto protoreflect.FileDescriptor

const file_fenzvideo_v1_tag_proto_rawDesc = "" +
	"\n" +
	"\x16fenzvideo/v1/tag.proto\x12\ffenzvideo.v1\x1a\x1cgoogle/api/annotations.proto\"\x11\n" +
	"\x0fListTagsRequest\"E\n" +
	"\x10GetMyTagsRequest\x12\"\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tH\x00R\tsessionId\x88\x01\x01B\r\n" +
	"\v_session_id\"^\n" +
	"\x10SetMyTagsRequest\x12\x17\n" +
	"\atag_ids\x18\x01 \x03(\x04R\x06tagIds\x12\"\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tH\x00R\tsessionId\x88\x01\x01B\r\n" +
	"\v_session_id\"9\n" +
	"\fTagListReply\x12)\n" +
	"\x04tags\x18\x01 \x03(\v2\x15.fenzvideo.v1.TagItemR\x04tags\"A\n" +
	"\aTagItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug2\xb0\x02\n" +
	"\n" +
	"TagService\x12[\n" +
	"\bListTags\x12\x1d.fenzvideo.v1.ListTagsRequest\x1a\x1a.fenzvideo.v1.TagListReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/tags\x12`\n" +
	"\tGetMyTags\x12\x1e.fenzvideo.v1.GetMyTagsRequest\x1a\x1a.fenzvideo.v1.TagListReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/tags/my\x12c\n" +
	"\tSetMyTags\x12\x1e.fenzvideo.v1.SetMyTagsRequest\x1a\x1a.fenzvideo.v1.TagListReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/api/v1/tags/myB\x1dZ\x1bbackend/api/fenzvideo/v1;v1b\x06proto3"

var (
	file_fenzvideo_v1_tag_proto_rawDescOnce sync.Once
	file_fenzvideo_v1_tag_proto_rawDescData []byte
)

func file_fenzvideo_v1_tag_proto_rawDescGZIP() []byte {
	file_fenzvideo_v1_tag_proto_rawDescOnce.Do(func() {
		file_fenzvideo_v1_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fenzvideo_v1_tag_proto_rawDesc), len(file_fenzvideo_v1_tag_proto_rawDesc)))
	})
	return file_fenzvideo_v1_tag_proto_rawDescData
}

var file_fenzvideo_v1_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_fenzvideo_v1_tag_proto_goTypes = []any{
	(*ListTagsRequest)(nil),  // 0: fenzvideo.v1.ListTagsRequest
	(*GetMyTagsRequest)(nil), // 1: fenzvideo.v1.GetMyTagsRequest
	(*SetMyTagsRequest)(nil), // 2: fenzvideo.v1.SetMyTagsRequest
	(*TagListReply)(nil),     // 3: fenzvideo.v1.TagListReply
	(*TagItem)(nil),          // 4: fenzvideo.v1.TagItem
}
var file_fenzvideo_v1_tag_proto_depIdxs = []int32{
	4, // 0: fenzvideo.v1.TagListReply.tags:type_name -> fenzvideo.v1.TagItem
	0, // 1: fenzvideo.v1.TagService.ListTags:input_type -> fenzvideo.v1.ListTagsRequest
	1, // 2: fenzvideo.v1.TagService.GetMyTags:input_type -> fenzvideo.v1.GetMyTagsRequest
	2, // 3: fenzvideo.v1.TagService.SetMyTags:input_type -> fenzvideo.v1.SetMyTagsRequest
	3, // 4: fenzvideo.v1.TagService.ListTags:output_type -> fenzvideo.v1.TagListReply
	3, // 5: fenzvideo.v1.TagService.GetMyTags:output_type -> fenzvideo.v1.TagListReply
	3, // 6: fenzvideo.v1.TagService.SetMyTags:output_type -> fenzvideo.v1.TagListReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fenzvideo_v1_tag_proto_init() }
func file_fenzvideo_v1_tag_proto_init() {
	if File_fenzvideo_v1_tag_proto != nil {
		return
	}
	file_fenzvideo_v1_tag_proto_msgTypes[1].OneofWrappers = []any{}
	file_fenzvideo_v1_tag_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fenzvideo_v1_tag_proto_rawDesc), len(file_fenzvideo_v1_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fenzvideo_v1_tag_proto_goTypes,
		DependencyIndexes: file_fenzvideo_v1_tag_proto_depIdxs,
		MessageInfos:      file_fenzvideo_v1_tag_proto_msgTypes,
	}.Build()
	File_fenzvideo_v1_tag_proto = out.File
	file_fenzvideo_v1_tag_proto_goTypes = nil
	file_fenzvideo_v1_tag_proto_depIdxs = nil
}
