// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: fenzvideo/v1/video.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CategoryId    uint64                 `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TagIds        []uint64               `protobuf:"varint,4,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	AccessTier    int32                  `protobuf:"varint,5,opt,name=access_tier,json=accessTier,proto3" json:"access_tier,omitempty"`
	Duration      uint32                 `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,7,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	ThumbnailUrl  *string                `protobuf:"bytes,8,opt,name=thumbnail_url,json=thumbnailUrl,proto3,oneof" json:"thumbnail_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVideoRequest) Reset() {
	*x = CreateVideoRequest{}
	mi := &file_fenzvideo_v1_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoRequest) ProtoMessage() {}

func (x *CreateVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoRequest.ProtoReflect.Descriptor instead.
func (*CreateVideoRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_video_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateVideoRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateVideoRequest) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateVideoRequest) GetTagIds() []uint64 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *CreateVideoRequest) GetAccessTier() int32 {
	if x != nil {
		return x.AccessTier
	}
	return 0
}

func (x *CreateVideoRequest) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CreateVideoRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *CreateVideoRequest) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

type UpdateVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CategoryId    *uint64                `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	TagIds        []uint64               `protobuf:"varint,5,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	AccessTier    *int32                 `protobuf:"varint,6,opt,name=access_tier,json=accessTier,proto3,oneof" json:"access_tier,omitempty"`
	ThumbnailUrl  *string                `protobuf:"bytes,7,opt,name=thumbnail_url,json=thumbnailUrl,proto3,oneof" json:"thumbnail_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVideoRequest) Reset() {
	*x = UpdateVideoRequest{}
	mi := &file_fenzvideo_v1_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoRequest) ProtoMessage() {}

func (x *UpdateVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoRequest.ProtoReflect.Descriptor instead.
func (*UpdateVideoRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_video_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateVideoRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateVideoRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateVideoRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateVideoRequest) GetCategoryId() uint64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *UpdateVideoRequest) GetTagIds() []uint64 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *UpdateVideoRequest) GetAccessTier() int32 {
	if x != nil && x.AccessTier != nil {
		return *x.AccessTier
	}
	return 0
}

func (x *UpdateVideoRequest) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

type GetVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoRequest) Reset() {
	*x = GetVideoRequest{}
	mi := &file_fenzvideo_v1_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoRequest) ProtoMessage() {}

func (x *GetVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoRequest.ProtoReflect.Descriptor instead.
func (*GetVideoRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_video_proto_rawDescGZIP(), []int{2}
}

func (x *GetVideoRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoRequest) Reset() {
	*x = DeleteVideoRequest{}
	mi := &file_fenzvideo_v1_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoRequest) ProtoMessage() {}

func (x *DeleteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoRequest.ProtoReflect.Descriptor instead.
func (*DeleteVideoRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_video_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteVideoRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteVideoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoReply) Reset() {
	*x = DeleteVideoReply{}
	mi := &file_fenzvideo_v1_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoReply) ProtoMessage() {}

func (x *DeleteVideoReply) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoReply.ProtoReflect.Descriptor instead.
func (*DeleteVideoReply) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_video_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteVideoReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TogglePublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsPublished   bool                   `protobuf:"varint,2,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TogglePublishRequest) Reset() {
	*x = TogglePublishRequest{}
	mi := &file_fenzvideo_v1_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TogglePublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TogglePublishRequest) ProtoMessage() {}

func (x *TogglePublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TogglePublishRequest.ProtoReflect.Descriptor instead.
func (*TogglePublishRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_video_proto_rawDescGZIP(), []int{5}
}

func (x *TogglePublishRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TogglePublishRequest) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

type GetRecommendedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *string                `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendedRequest) Reset() {
	*x = GetRecommendedRequest{}
	mi := &file_fenzvideo_v1_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendedRequest) ProtoMessage() {}

func (x *GetRecommendedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendedRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendedRequest) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_video_proto_rawDescGZIP(), []int{6}
}

func (x *GetRecommendedRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *GetRecommendedRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRecommendedRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type VideoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	CategoryId    uint64                 `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,5,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,8,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,9,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Duration      uint32                 `protobuf:"varint,10,opt,name=duration,proto3" json:"duration,omitempty"`
	Views         uint64                 `protobuf:"varint,11,opt,name=views,proto3" json:"views,omitempty"`
	AccessTier    int32                  `protobuf:"varint,12,opt,name=access_tier,json=accessTier,proto3" json:"access_tier,omitempty"`
	IsPublished   bool                   `protobuf:"varint,13,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	Tags          []*TagItem             `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoReply) Reset() {
	*x = VideoReply{}
	mi := &file_fenzvideo_v1_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoReply) ProtoMessage() {}

func (x *VideoReply) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoReply.ProtoReflect.Descriptor instead.
func (*VideoReply) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_video_proto_rawDescGZIP(), []int{7}
}

func (x *VideoReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VideoReply) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VideoReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VideoReply) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *VideoReply) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *VideoReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoReply) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *VideoReply) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *VideoReply) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *VideoReply) GetViews() uint64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *VideoReply) GetAccessTier() int32 {
	if x != nil {
		return x.AccessTier
	}
	return 0
}

func (x *VideoReply) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *VideoReply) GetTags() []*TagItem {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *VideoReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type VideoListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoReply          `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoListReply) Reset() {
	*x = VideoListReply{}
	mi := &file_fenzvideo_v1_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoListReply) ProtoMessage() {}

func (x *VideoListReply) ProtoReflect() protoreflect.Message {
	mi := &file_fenzvideo_v1_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoListReply.ProtoReflect.Descriptor instead.
func (*VideoListReply) Descriptor() ([]byte, []int) {
	return file_fenzvideo_v1_video_proto_rawDescGZIP(), []int{8}
}

func (x *VideoListReply) GetVideos() []*VideoReply {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *VideoListReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_fenzvideo_v1_video_proto protoreflect.FileDescriptor

const file_fenzvideo_v1_video_proto_rawDesc = "" +
	"\n" +
	"\x18fenzvideo/v1/video.proto\x12\ffenzvideo.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x16fenzvideo/v1/tag.proto\"\xb1\x02\n" +
	"\x12CreateVideoRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x04R\n" +
	"categoryId\x12\x17\n" +
	"\atag_ids\x18\x04 \x03(\x04R\x06tagIds\x12\x1f\n" +
	"\vaccess_tier\x18\x05 \x01(\x05R\n" +
	"accessTier\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\rR\bduration\x12\x1b\n" +
	"\tvideo_url\x18\a \x01(\tR\bvideoUrl\x12(\n" +
	"\rthumbnail_url\x18\b \x01(\tH\x01R\fthumbnailUrl\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_thumbnail_url\"\xc1\x02\n" +
	"\x12UpdateVideoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12$\n" +
	"\vcategory_id\x18\x04 \x01(\x04H\x02R\n" +
	"categoryId\x88\x01\x01\x12\x17\n" +
	"\atag_ids\x18\x05 \x03(\x04R\x06tagIds\x12$\n" +
	"\vaccess_tier\x18\x06 \x01(\x05H\x03R\n" +
	"accessTier\x88\x01\x01\x12(\n" +
	"\rthumbnail_url\x18\a \x01(\tH\x04R\fthumbnailUrl\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_category_idB\x0e\n" +
	"\f_access_tierB\x10\n" +
	"\x0e_thumbnail_url\"!\n" +
	"\x0fGetVideoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"$\n" +
	"\x12DeleteVideoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\",\n" +
	"\x10DeleteVideoReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\x14TogglePublishRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\fis_published\x18\x02 \x01(\bR\visPublished\"{\n" +
	"\x15GetRecommendedRequest\x12\"\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tH\x00R\tsessionId\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSizeB\r\n" +
	"\v_session_id\"\xd1\x03\n" +
	"\n" +
	"VideoReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x04R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x05 \x01(\tR\fcategoryName\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1b\n" +
	"\tvideo_url\x18\b \x01(\tR\bvideoUrl\x12#\n" +
	"\rthumbnail_url\x18\t \x01(\tR\fthumbnailUrl\x12\x1a\n" +
	"\bduration\x18\n" +
	" \x01(\rR\bduration\x12\x14\n" +
	"\x05views\x18\v \x01(\x04R\x05views\x12\x1f\n" +
	"\vaccess_tier\x18\f \x01(\x05R\n" +
	"accessTier\x12!\n" +
	"\fis_published\x18\r \x01(\bR\visPublished\x12)\n" +
	"\x04tags\x18\x0e \x03(\v2\x15.fenzvideo.v1.TagItemR\x04tags\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\"X\n" +
	"\x0eVideoListReply\x120\n" +
	"\x06videos\x18\x01 \x03(\v2\x18.fenzvideo.v1.VideoReplyR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\x98\x05\n" +
	"\fVideoService\x12d\n" +
	"\vCreateVideo\x12 .fenzvideo.v1.CreateVideoRequest\x1a\x18.fenzvideo.v1.VideoReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/videos\x12`\n" +
	"\bGetVideo\x12\x1d.fenzvideo.v1.GetVideoRequest\x1a\x18.fenzvideo.v1.VideoReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/videos/{id}\x12i\n" +
	"\vUpdateVideo\x12 .fenzvideo.v1.UpdateVideoRequest\x1a\x18.fenzvideo.v1.VideoReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/api/v1/videos/{id}\x12l\n" +
	"\vDeleteVideo\x12 .fenzvideo.v1.DeleteVideoRequest\x1a\x1e.fenzvideo.v1.DeleteVideoReply\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/v1/videos/{id}\x12u\n" +
	"\rTogglePublish\x12\".fenzvideo.v1.TogglePublishRequest\x1a\x18.fenzvideo.v1.VideoReply\"&\x82\xd3\xe4\x93\x02 :\x01*2\x1b/api/v1/videos/{id}/publish\x12p\n" +
	"\x0eGetRecommended\x12#.fenzvideo.v1.GetRecommendedRequest\x1a\x1c.fenzvideo.v1.VideoListReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/recommendedB\x1dZ\x1bbackend/api/fenzvideo/v1;v1b\x06proto3"

var (
	file_fenzvideo_v1_video_proto_rawDescOnce sync.Once
	file_fenzvideo_v1_video_proto_rawDescData []byte
)

func file_fenzvideo_v1_video_proto_rawDescGZIP() []byte {
	file_fenzvideo_v1_video_proto_rawDescOnce.Do(func() {
		file_fenzvideo_v1_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fenzvideo_v1_video_proto_rawDesc), len(file_fenzvideo_v1_video_proto_rawDesc)))
	})
	return file_fenzvideo_v1_video_proto_rawDescData
}

var file_fenzvideo_v1_video_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_fenzvideo_v1_video_proto_goTypes = []any{
	(*CreateVideoRequest)(nil),    // 0: fenzvideo.v1.CreateVideoRequest
	(*UpdateVideoRequest)(nil),    // 1: fenzvideo.v1.UpdateVideoRequest
	(*GetVideoRequest)(nil),       // 2: fenzvideo.v1.GetVideoRequest
	(*DeleteVideoRequest)(nil),    // 3: fenzvideo.v1.DeleteVideoRequest
	(*DeleteVideoReply)(nil),      // 4: fenzvideo.v1.DeleteVideoReply
	(*TogglePublishRequest)(nil),  // 5: fenzvideo.v1.TogglePublishRequest
	(*GetRecommendedRequest)(nil), // 6: fenzvideo.v1.GetRecommendedRequest
	(*VideoReply)(nil),            // 7: fenzvideo.v1.VideoReply
	(*VideoListReply)(nil),        // 8: fenzvideo.v1.VideoListReply
	(*TagItem)(nil),               // 9: fenzvideo.v1.TagItem
}
var file_fenzvideo_v1_video_proto_depIdxs = []int32{
	9, // 0: fenzvideo.v1.VideoReply.tags:type_name -> fenzvideo.v1.TagItem
	7, // 1: fenzvideo.v1.VideoListReply.videos:type_name -> fenzvideo.v1.VideoReply
	0, // 2: fenzvideo.v1.VideoService.CreateVideo:input_type -> fenzvideo.v1.CreateVideoRequest
	2, // 3: fenzvideo.v1.VideoService.GetVideo:input_type -> fenzvideo.v1.GetVideoRequest
	1, // 4: fenzvideo.v1.VideoService.UpdateVideo:input_type -> fenzvideo.v1.UpdateVideoRequest
	3, // 5: fenzvideo.v1.VideoService.DeleteVideo:input_type -> fenzvideo.v1.DeleteVideoRequest
	5, // 6: fenzvideo.v1.VideoService.TogglePublish:input_type -> fenzvideo.v1.TogglePublishRequest
	6, // 7: fenzvideo.v1.VideoService.GetRecommended:input_type -> fenzvideo.v1.GetRecommendedRequest
	7, // 8: fenzvideo.v1.VideoService.CreateVideo:output_type -> fenzvideo.v1.VideoReply
	7, // 9: fenzvideo.v1.VideoService.GetVideo:output_type -> fenzvideo.v1.VideoReply
	7, // 10: fenzvideo.v1.VideoService.UpdateVideo:output_type -> fenzvideo.v1.VideoReply
	4, // 11: fenzvideo.v1.VideoService.DeleteVideo:output_type -> fenzvideo.v1.DeleteVideoReply
	7, // 12: fenzvideo.v1.VideoService.TogglePublish:output_type -> fenzvideo.v1.VideoReply
	8, // 13: fenzvideo.v1.VideoService.GetRecommended:output_type -> fenzvideo.v1.VideoListReply
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fenzvideo_v1_video_proto_init() }
func file_fenzvideo_v1_video_proto_init() {
	if File_fenzvideo_v1_video_proto != nil {
		return
	}
	file_fenzvideo_v1_tag_proto_init()
	file_fenzvideo_v1_video_proto_msgTypes[0].OneofWrappers = []any{}
	file_fenzvideo_v1_video_proto_msgTypes[1].OneofWrappers = []any{}
	file_fenzvideo_v1_video_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fenzvideo_v1_video_proto_rawDesc), len(file_fenzvideo_v1_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fenzvideo_v1_video_proto_goTypes,
		DependencyIndexes: file_fenzvideo_v1_video_proto_depIdxs,
		MessageInfos:      file_fenzvideo_v1_video_proto_msgTypes,
	}.Build()
	File_fenzvideo_v1_video_proto = out.File
	file_fenzvideo_v1_video_proto_goTypes = nil
	file_fenzvideo_v1_video_proto_depIdxs = nil
}
